services:
  - type: web
    name: taskio-backend
    runtime: docker
    plan: free
    healthCheckPath: /api/tasks
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
